export {default as Home} from './Home'
export {default as Shop} from './Shop'
export {default as Login} from './Login'
export {default as Registere} from './Registere'
export {default as Cart} from './Cart'
